import './globals.css'
import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'

import Header from './components/Header'

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['400', '600', '700', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={mulish.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
