const projectsConstants = [
  {
    id: 1,
    title: 'Promptopia',
    description: 'Descrição do Projeto 1',
    img: '/projeto01.jpg',
    repositoryUrl: 'https://github.com/LxLorenzo/Promptopia',
    projectUrl: 'https://promptopia-lxlorenzo.vercel.app/',
    icons: [
      'SiNextdotjs',
      'SiTypescript',
      'SiMongodb',
      'SiMongoose',
      'SiTailwindcss',
    ],
  },
  {
    id: 2,
    title: 'FSW Trips',
    description: 'Descrição do Projeto 2',
    img: '/projeto02.jpg',
    repositoryUrl: 'https://github.com/LxLorenzo/fsw-trips',
    projectUrl: 'https://fsw-trips-lxlorenzo.vercel.app/',
    icons: [
      'SiNextdotjs',
      'SiTypescript',
      'SiPrisma',
      'SiSupabase',
      'SiStripe',
      'SiTailwindcss',
    ],
  },
  {
    id: 3,
    title: 'Gericht',
    description: 'Descrição do Projeto 3',
    img: '/projeto03.jpg',
    repositoryUrl: 'https://github.com/LxLorenzo/gericht-restaurant',
    projectUrl: 'https://gerich-restaurant.vercel.app/',
    icons: ['SiReact', 'SiCss3'],
  },
  {
    id: 4,
    title: 'HooBank',
    description: 'Descrição do Projeto 4',
    img: '/projeto04.jpg',
    repositoryUrl: 'https://github.com/LxLorenzo/bank_modern_app',
    projectUrl: 'https://bank-modern-app.vercel.app/',
    icons: ['SiReact', 'SiVite', 'SiTailwindcss'],
  },
  {
    id: 5,
    title: 'GPT-Project',
    description: 'Descrição do Projeto 5',
    img: '/projeto05.jpg',
    repositoryUrl: 'https://github.com/LxLorenzo/gptproject',
    projectUrl: 'https://gptproject.vercel.app/',
    icons: ['SiReact', 'SiCss3'],
  },
  {
    id: 6,
    title: 'Multi-Step-Form',
    description: 'Descrição do Projeto 6',
    img: '/projeto06.jpg',
    repositoryUrl: 'https://github.com/LxLorenzo/Multi-Step-Form',
    projectUrl: 'https://lxlorenzo.github.io/Multi-Step-Form/',
    icons: ['SiHtml5', 'SiCss3', 'SiJavascript'],
  },
]

export default projectsConstants
